# This file filters out only IPXO specific records.

import pandas as pd
import argparse
import os

# This works for only parquet files.
IPXO_ASN = 'AS834'
IPXO_REPO_URI = 'r.magellan.ipxo.com'

def main(input_file, output_file):
    print("\n*************************************************************************************")
    print("\n-------------------------- RPKI ROA IPXO FILTERING ----------------------------------")
    print("\n*************************************************************************************")
    print(f"\nLoading data from {input_file}...")
    try:
        df = pd.read_parquet(input_file)
        print(f" * Successfully loaded {len(df):,} total ROA records.")
    except Exception as e:
        print(f"!!ERROR: Could not read the input file '{input_file}'. Please check the path.")
        print(e)
        return

    print(f" * Filtering records for ASN {IPXO_ASN} or URI containing '{IPXO_REPO_URI}'")
    
    ipxo_related_mask = (df['asn'] == IPXO_ASN) | (df['uri'].str.contains(IPXO_REPO_URI, na=False))
    
    filtered_df = df[ipxo_related_mask].copy()
    
    if filtered_df.empty:
        print("!!WARNING: No IPXO-related records were found.")
        return

    print(f" ** Filtering complete. Found {len(filtered_df)} IPXO-related records.")

    try:
        output_dir = os.path.dirname(output_file)
        if output_dir:
            os.makedirs(output_dir, exist_ok=True)
            
        filtered_df.to_parquet(output_file, index=False)
        print(f"\nSuccessfully saved IPXO filtered data to {output_file}\n")
    except Exception as e:
        print(f"!!ERROR: Could not save the output file '{output_file}'.")
        print(e)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Filter RPKI ROA Parquet data for IPXO-related records from Parquet files.")
    
    parser.add_argument(
        '--input_file', 
        type=str, 
        required=True,
        help="Path to the input Parquet file generated by the parsing script."
    )
    
    parser.add_argument(
        '--output_file', 
        type=str, 
        required=True,
        help="Path for the output filtered Parquet file."
    )

    args = parser.parse_args()
    main(args.input_file, args.output_file)